---
- name: Update
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Unarchive files
  become: yes
  unarchive:
    src: "files/artifact.tar.gz"
    dest: .

- name: "Start application"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
